# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZgE76XtMCWgr7460e7lg5vHZyLYjgdc
"""

!pip install langchain-openai
!pip install requests

!pip uninstall -y langchain langchain-core langchain-openai
!pip install "langchain==0.1.20" "langchain-openai==0.0.8" streamlit requests
!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import os
# import streamlit as st
# from langchain_openai import ChatOpenAI
# from langchain.agents import initialize_agent, AgentType
# from langchain.tools import tool

# ------------------- IMPORTS -------------------

import os
import streamlit as st
from langchain_openai import ChatOpenAI
from langchain.agents import initialize_agent, AgentType
from langchain.tools import tool

# --------------- API KEY SETUP -----------------
# REPLACE WITH YOUR OWN NEW KEY
os.environ["OPENAI_API_KEY"] = "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"   # do not share this anywher


# ------------------- CORE FUNCTIONS -------------------

def search_flights(source: str, destination: str):
    """Simulates searching for flights."""
    return {
        "flight_price": 15000.00,
        "details": f"Flight from {source} to {destination} available."
    }


def search_hotels(city: str):
    """Simulates searching for hotels."""
    return {
        "hotel_price_per_night": 5000.00,
        "details": f"Best hotel in {city} is ABC Hotel."
    }


def recommend_places(city: str):
    """Simulates recommending places to visit."""
    return {
        "places": ["Beach A", "Temple B", "Market C"],
        "details": f"Top places in {city}."
    }


def get_weather(latitude: float, longitude: float, start_date: str, end_date: str):
    """Simulates getting weather forecast."""
    return {
        "forecast": "Sunny with occasional clouds",
        "temperature": "28°C"
    }


def estimate_budget(flight_price: float, hotel_price: float, nights: int):
    """Estimates total trip budget."""
    total_budget = flight_price + (hotel_price * nights)
    return {
        "total_budget": total_budget,
        "currency": "INR"
    }


# ------------------- TOOLS -------------------

@tool
def flight_tool(source: str, destination: str):
    """Search flights by source and destination."""
    return search_flights(source, destination)


@tool
def hotel_tool(city: str):
    """Search hotels in a city."""
    return search_hotels(city)


@tool
def places_tool(city: str):
    """Recommend tourist places."""
    return recommend_places(city)


@tool
def weather_tool(latitude: float, longitude: float, start_date: str, end_date: str):
    """Get weather for given coordinates."""
    return get_weather(latitude, longitude, start_date, end_date)


@tool
def budget_tool(flight_price: float, hotel_price: float, nights: int):
    """Estimate travel budget."""
    return estimate_budget(flight_price, hotel_price, nights)


# ------------------- LLM -------------------

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0.3
)

# ------------------- TOOL LIST -------------------

tools = [
    flight_tool,
    hotel_tool,
    places_tool,
    weather_tool,
    budget_tool
]

# ------------------- AGENT -------------------

agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent=AgentType.OPENAI_FUNCTIONS,
    verbose=True
)

# ------------------- STREAMLIT UI -------------------
st.title("✈️ AI Travel Planning Agent")

source = st.text_input("From City")
destination = st.text_input("To City")
days = st.number_input("Number of Days", min_value=1, max_value=15, value=3)

if st.button("Plan My Trip"):
    query = f"""
    Plan a {days}-day trip from {source} to {destination}.
    Include flights, hotels, weather, tourist places, and total budget.
    """
    result = agent.invoke(query)
    st.subheader("Trip Plan Result")
    st.write(result)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
#

!streamlit run app.py

from google.colab import files
files.download("app.py")
